# SixFifty GE2017 Model
## Create modelling datasets
For more information please see [SixFifty.org.uk](https://sixfifty.org.uk) or the [SixFifty Hackathon repo](https://github.com/six50/hackathon).

## Import datasets and pre-flight checks

In [1]:
# Libaries
import feather
import matplotlib
import numpy as np
from pathlib import Path
import pandas as pd

# Config
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
DATA_DIR = Path('../data/')
%matplotlib inline

Running `data/retrieve_data.py` from the `hackathon` repo root will download the following datasets into the required location.

In [2]:
ge_data_dir = DATA_DIR / 'general_election' / 'electoral_commission' / 'results'
ge_2010 = pd.read_feather(ge_data_dir / 'ge_2010_results.feather')
ge_2015 = pd.read_feather(ge_data_dir / 'ge_2015_results.feather')

In [3]:
ge_2010.head(3)

,Press Association Reference,Constituency Name,Region,Election Year,Electorate,Votes,AC,AD,AGS,APNI,APP,AWL,AWP,BB,BCP,Bean,Best,BGPV,BIB,BIC,Blue,BNP,BP Elvis,C28,Cam Soc,CG,Ch M,Ch P,CIP,CITY,CNPG,Comm,Comm L,Con,Cor D,CPA,CSP,CTDP,CURE,D Lab,D Nat,DDP,DUP,ED,EIP,EPA,FAWG,FDP,FFR,Grn,GSOT,Hum,ICHC,IEAC,IFED,ILEU,Impact,Ind1,Ind2,Ind3,Ind4,Ind5,IPT,ISGB,ISQM,IUK,IVH,IZB,JAC,Joy,JP,Lab,Land,LD,Lib,Libert,LIND,LLPB,LTT,MACI,MCP,MEDI,MEP,MIF,MK,MPEA,MRLP,MRP,Nat Lib,NCDV,ND,New,NF,NFP,NICF,Nobody,NSPS,PBP,PC,Pirate,PNDP,Poet,PPBF,PPE,PPNV,Reform,Respect,Rest,RRG,RTBP,SACL,Sci,SDLP,SEP,SF,SIG,SJP,SKGP,SMA,SMRA,SNP,Soc,Soc Alt,Soc Dem,Soc Lab,South,Speaker,SSP,TF,TOC,Trust,TUSC,TUV,UCUNF,UKIP,UPS,UV,VCCA,Vote,Wessex Reg,WRP,You,Youth,YRDPL
0,1.0,Aberavon,Wales,2010.0,50838.0,30958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,558.0,0.0,0.0,0.0,0.0,0.0,1276.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4411.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,919.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16073.0,0.0,5034.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2198.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,Aberconwy,Wales,2010.0,44593.0,29966,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.0,0.0,0.0,0.0,0.0,0.0,10734.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7336.0,0.0,5786.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5341.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,632.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,Aberdeen North,Scotland,2010.0,64808.0,37701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,635.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16746.0,0.0,7001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8385.0,0.0,0.0,0.0,0.0,0.0,0.0,268.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
ge_2015.head(3)

,Press Association ID Number,Constituency ID,Constituency Name,Constituency Type,County,Region ID,Region,Country,Election Year,Electorate,Valid Votes,30-50,Above,Active Dem,AD,Alliance,AP,Apni,Atom,AWP,Beer BS,Birthday,BNP,Bournemouth,Bristol,Brit Dem,Brit Ind,C,Campaign,Change,Ch M,Ch P,Christian,Class War,Comm,Comm Brit,Comm Lge,Communist,Community,Consensus,CPA,Croydon,CSA,CSP,Dem Ref,Digital,DP,DUP,Eccentric,Elmo,Eng Dem,EP,FPT,Green,Green Soc,Guildford,Hoi,Hospital,Humanity,IASI,IE,Ind,Ind2,Ind CHC,IPAP,ISWSL,IZB,JACP,JMB,Lab,Lab Co-op,LD,Lib,Lib GB,Lincs Ind,Loony,LP,LU,Magna Carta,Mainstream,Manston,Meb Ker,Nat Lib,ND,NE Party,New IC,NF,NHAP,Northern,Patria,PBP,PC,Peace,PF,Pilgrim,Pirate,Plural,Poole,PPP,PP UK,PSP,Real,Realist,Reality,Rep Soc,Respect,Restore,RFAC,Rochdale,Roman,RTP,Scottish CP,SCP,SDLP,SEP,SF,S New,SNP,Soc Dem,Soc Lab,Song,Southport,Speaker,SPGB,SSP,TEP,Thanet,TSPP,TUSC,TUV,Ubuntu,UKIP,UKPDP,U Party,Uttlesford,UUP,Vapers,VAT,Wessex Reg,Whig,Wigan,Worth,WP,WRP,WVPTFP,Yorks,Young,Zeb
0,1.0,W07000049,Aberavon,County,West Glamorgan,W92000004,Wales,Wales,2015.0,49821.0,31523.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3742.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,711.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1137.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15416.0,0.0,1397.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3663.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,352.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,134.0,0.0,0.0,4971.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,W07000058,Aberconwy,County,Clwyd,W92000004,Wales,Wales,2015.0,45525.0,30148.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12513.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,727.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8514.0,0.0,1391.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3536.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3467.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,S14000001,Aberdeen North,Burgh,Scotland,S92000003,Scotland,Scotland,2015.0,67745.0,43936.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5304.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11397.0,2050.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,186.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24793.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,206.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Before we get into the modelling, there's a bit of cleanup to do and a few checks to run:
- [Some MPs](https://en.wikipedia.org/wiki/Labour_Co-operative) are members of _both_ the [Labour Party](www.labour.org.uk) and the [Co-operative Party](http://www.party.coop/), which plays havoc with modelling. We will therefore consider them all members of the Labour party.
- Check that there are all constituencies in the 2010 data are also in 2015 data, and vice versa.
- Create `country_lookup`, a dictionary that returns the country of any constituency given its PANO (Press Association ID Number).

In [5]:
parties_lookup_2010 = {
    'Con': 'con',
    'Lab': 'lab',
    'LD': 'ld',
    'UKIP': 'ukip',
    'Grn': 'grn',
    'Other': 'other'
}
parties_15 = list(parties_lookup_2010.values())

In [6]:
parties_lookup_2015 = {
    'C': 'con',
    'Lab': 'lab',
    'LD': 'ld',
    'UKIP': 'ukip',
    'Green': 'grn',
    'SNP': 'snp',
    'PC': 'pc',
    'Other': 'other'
}
parties_17 = list(parties_lookup_2015.values())

In [7]:
# Merge Labour and Coop
ge_2015['Lab'] = ge_2015['Lab'] + ge_2015['Lab Co-op']
del ge_2015['Lab Co-op']

In [8]:
# Check constituencies are mergeable
print(set(ge_2010['Press Association Reference']).difference(set(ge_2015['Press Association ID Number'])))  # should be empty set
print(set(ge_2015['Press Association ID Number']).difference(set(ge_2010['Press Association Reference'])))  # should be empty set
print(len(ge_2010), len(ge_2010['Press Association Reference']))  # should both be 650
print(len(ge_2015), len(ge_2015['Press Association ID Number']))  # should both be 650

set()
set()
650 650
650 650

In [9]:
# Make PANO -> geo lookup
geo_lookup = [(x[1][0], x[1][1]) for x in ge_2015[['Press Association ID Number', 'Country']].iterrows()]
geo_lookup = dict(geo_lookup)
print(geo_lookup[14.0])  # should be "Northern Ireland"
# Add London boroughs
london_panos = ge_2015[ge_2015['County'] == 'London']['Press Association ID Number'].values
for pano in london_panos:
    geo_lookup[pano] = 'London'
print(geo_lookup[237.0])  # should be "London"
# Rename other England
for k in geo_lookup:
    if geo_lookup[k] == 'England':
        geo_lookup[k] = 'England_not_london'
    elif geo_lookup[k] == 'Northern Ireland':
        geo_lookup[k] = 'NI'

Northern Ireland
London

## 2015 polling

In [10]:
polls_data_dir = DATA_DIR / 'polls'

In [11]:
# Latest polling data (3 days before election, i.e. if election on 7th May 2015, polls as of 4th May)
polls = pd.read_feather(polls_data_dir / 'polls.feather')
polls.head()

,company,client,method,from,to,sample_size,con,lab,ld,ukip,grn,snp,pdf
0,Ipsos MORI,FT,None,NaT,2005-05-19,NaN,0.30,0.37,0.26,NaN,NaN,NaN,None
1,Ipsos MORI,First Tuesday,None,NaT,2005-05-19,NaN,0.27,0.40,0.26,NaN,NaN,NaN,None
2,YouGov,Telegraph,None,NaT,2005-05-24,NaN,0.31,0.38,0.23,NaN,NaN,NaN,None
3,Ipsos MORI,Social Research Institute,None,NaT,2005-06-16,NaN,0.29,0.42,0.21,NaN,NaN,NaN,None
4,ICM,Guardian,None,NaT,2005-06-17,NaN,0.31,0.38,0.23,NaN,NaN,NaN,None

In [12]:
pollsters = polls[(polls.to >= '2015-04-04') & (polls.to <= '2015-05-04')].company.unique()
pollsters

array(['YouGov', 'Populus', 'Kantar TNS', 'ComRes', 'Survation',
       'Opinium', 'Panelbase', 'ICM', 'Ashcroft', 'Ipsos MORI', 'BMG'],
      dtype=object)

In [13]:
# Use single last poll from each pollster in final week of polling then average out
polls = polls[(polls.to >= '2015-04-01') & (polls.to <= '2015-05-07')]
pop = polls.loc[:0]
for p in pollsters:
    pop = pop.append(polls[polls.company == p].tail(1))
pop

,company,client,method,from,to,sample_size,con,lab,ld,ukip,grn,snp,pdf
2691,YouGov,Sun,None,NaT,2015-05-06,NaN,0.34,0.34,0.10,0.12,0.04,NaN,None
2680,Populus,FT,None,NaT,2015-05-04,NaN,0.34,0.34,0.10,0.13,0.05,NaN,None
2678,Kantar TNS,None,None,NaT,2015-05-04,NaN,0.33,0.32,0.08,0.14,0.06,NaN,None
2690,ComRes,Daily Mail/ITV News,None,NaT,2015-05-06,NaN,0.35,0.34,0.09,0.12,0.04,NaN,None
2689,Survation,Mirror,None,NaT,2015-05-06,NaN,0.33,0.33,0.09,0.16,0.04,NaN,None
2693,Opinium,None,None,NaT,2015-05-06,NaN,0.35,0.34,0.08,0.12,0.06,NaN,None
2692,Panelbase,None,None,NaT,2015-05-06,NaN,0.31,0.33,0.08,0.16,0.05,NaN,None
2686,ICM,Guardian,None,NaT,2015-05-06,NaN,0.34,0.35,0.09,0.11,0.04,NaN,None
2688,Ashcroft,None,None,NaT,2015-05-06,NaN,0.33,0.33,0.10,0.11,0.06,NaN,None
2687,Ipsos MORI,Evening Standard,None,NaT,2015-05-06,NaN,0.36,0.35,0.08,0.11,0.05,NaN,None
2682,BMG,May-15,None,NaT,2015-05-05,NaN,0.34,0.34,0.10,0.12,0.04,NaN,None

In [14]:
# Create new polls dictionary by geo containing simple average across all pollsters
polls = {'UK': {}}
for p in ['con', 'lab', 'ld', 'ukip', 'grn']:
    polls['UK'][p] = pop[p].mean()
polls['UK'] = pd.Series(polls['UK'])
polls['UK']

con     0.338182
grn     0.048182
lab     0.337273
ld      0.090000
ukip    0.127273
dtype: float64

In [15]:
# Scotland, Wales, NI, London not available in 2015 data (we haven't extracted them yet!)
# Add Other
for geo in ['UK']:
    if 'other' not in polls[geo]:
        polls[geo]['other'] = 1 - sum(polls[geo])

In [16]:
# Reweight to 100%
for geo in ['UK']:
    polls[geo] = polls[geo] / polls[geo].sum()
polls

{'UK': con      0.338182
 grn      0.048182
 lab      0.337273
 ld       0.090000
 ukip     0.127273
 other    0.059091
 dtype: float64}

## 2017 polling

In [17]:
# Latest polling data
polls_17 = {'UK': {}}
polls_17_uk = pd.read_feather(polls_data_dir / 'polls.feather')
# Filter to recent data
polls_17_uk = polls_17_uk[polls_17_uk.to >= '2017-06-06']
# Add parties
for p in ['con', 'lab', 'ld', 'ukip', 'grn', 'snp']:
    polls_17['UK'][p] = (polls_17_uk.sample_size * polls_17_uk[p]).sum() / polls_17_uk.sample_size.sum()
polls_17['UK'] = pd.Series(polls_17['UK'], index=['con', 'lab', 'ld', 'ukip', 'snp', 'grn'])
polls_17

{'UK': con     0.426130
 lab     0.371942
 ld      0.070578
 ukip    0.041625
 snp     0.038982
 grn     0.019173
 dtype: float64}

In [18]:
# Repeat for Scotland polling...
polls_17['Scotland'] = {}
polls_17_tmp = pd.read_feather(polls_data_dir / 'polls_scotland.feather')
polls_17_tmp = polls_17_tmp[polls_17_tmp.to >= '2017-06-05']
for p in ['con', 'lab', 'ld', 'ukip', 'snp', 'grn']:
    polls_17['Scotland'][p] = (polls_17_tmp.sample_size * polls_17_tmp[p]).sum() / polls_17_tmp.sample_size.sum()
polls_17['Scotland'] = pd.Series(polls_17['Scotland'], index=['con', 'lab', 'ld', 'ukip', 'snp', 'grn'])
polls_17['Scotland']

con     0.271401
lab     0.236513
ld      0.053923
ukip    0.003895
snp     0.418192
grn     0.010513
dtype: float64

In [19]:
# ...and Wales
polls_17['Wales'] = {}
polls_17_tmp = pd.read_feather(polls_data_dir / 'polls_wales.feather')
polls_17_tmp = polls_17_tmp[polls_17_tmp.to >= '2017-06-07']
for p in ['con', 'lab', 'ld', 'ukip', 'pc', 'grn']:
    polls_17['Wales'][p] = (polls_17_tmp.sample_size * polls_17_tmp[p]).sum() / polls_17_tmp.sample_size.sum()
polls_17['Wales'] = pd.Series(polls_17['Wales'], index=['con', 'lab', 'ld', 'ukip', 'pc', 'grn'])
polls_17['Wales']

con     0.314166
lab     0.430377
ld      0.044139
ukip    0.045792
pc      0.148997
grn     0.000783
dtype: float64

In [20]:
# NI
polls_17['NI'] = (pd.read_feather(polls_data_dir / 'polls_ni_smoothed.feather')
                    .sort_values(by='date', ascending=False).iloc[0])
del polls_17['NI']['date']

# Collate all NI parties under other
for k in polls_17['NI'].index:
    if k not in parties_17:
        del polls_17['NI'][k]

del polls_17['NI']['other']
polls_17['NI']

grn     0.006
ukip    0.001
con     0.002
Name: 5, dtype: object

In [21]:
# London
polls_17['London'] = {}
polls_17_tmp = pd.read_feather(polls_data_dir / 'polls_london.feather')
polls_17_tmp = polls_17_tmp[polls_17_tmp.to >= '2017-05-31']
for p in ['con', 'lab', 'ld', 'ukip', 'grn']:
    polls_17['London'][p] = (polls_17_tmp.sample_size * polls_17_tmp[p]).sum() / polls_17_tmp.sample_size.sum()
polls_17['London'] = pd.Series(polls_17['London'], index=['con', 'lab', 'ld', 'ukip', 'grn'])
polls_17['London']

con     0.376424
lab     0.458455
ld      0.104133
ukip    0.031145
grn     0.021655
dtype: float64

In [22]:
# Estimate polling for England excluding London
survation_wts = {
    # from http://survation.com/wp-content/uploads/2017/06/Final-MoS-Post-BBC-Event-Poll-020617SWCH-1c0d4h9.pdf
    'Scotland': 85,
    'England': 881,
    'Wales': 67,
    'London': 137,
    'NI': 16
}
survation_wts['England_not_london'] = survation_wts['England'] - survation_wts['London']
survation_wts['UK'] = survation_wts['Scotland'] + survation_wts['England'] + survation_wts['Wales'] + survation_wts['NI']

def calculate_england_not_london(party):
    out = polls_17['UK'][party] * survation_wts['UK']
    for geo in ['Scotland', 'Wales', 'NI', 'London']:
        if party in polls_17[geo]:
            out = out - polls_17[geo][party] * survation_wts[geo]
    out = out / survation_wts['England_not_london']
    return out

polls_17['England_not_london'] = {'pc': 0, 'snp': 0}
for party in ['con', 'lab', 'ld', 'ukip', 'grn']:
    polls_17['England_not_london'][party] = calculate_england_not_london(party)

polls_17['England_not_london'] = pd.Series(polls_17['England_not_london'])
polls_17['England_not_london']

con     0.472164
grn     0.021644
lab     0.374221
ld      0.070201
pc      0.000000
snp     0.000000
ukip    0.048364
dtype: float64

In [23]:
# Fill in the gaps
for geo in ['UK', 'Scotland', 'Wales', 'NI', 'London', 'England_not_london']:
    for party in ['con', 'lab', 'ld', 'ukip', 'grn', 'snp', 'pc']:
        if party not in polls_17[geo]:
            print("Adding {} to {}".format(party, geo))
            polls_17[geo][party] = 0

Adding pc to UK
Adding pc to Scotland
Adding snp to Wales
Adding lab to NI
Adding ld to NI
Adding snp to NI
Adding pc to NI
Adding snp to London
Adding pc to London

In [24]:
# Fix PC (Plaid Cymru) for UK
polls_17['UK']['pc'] = polls_17['Wales']['pc'] * survation_wts['Wales'] / survation_wts['UK']

In [25]:
# Add Other
for geo in ['UK', 'Scotland', 'Wales', 'NI', 'London', 'England_not_london']:
    if 'other' not in polls_17[geo]:
        polls_17[geo]['other'] = 1 - sum(polls_17[geo])

# This doesn't work for UK or England_not_london; set current other polling to match 2015 result
polls_17['UK']['other'] = 0.03 # ge.other.sum() / ge['Valid Votes'].sum()
polls_17['England_not_london']['other'] = 0.01 # ge[ge.geo == 'England_not_london'].other.sum() / ge[ge.geo == 'England_not_london']['Valid Votes'].sum()

In [26]:
# Reweight to 100%
for geo in ['UK', 'Scotland', 'Wales', 'NI', 'London', 'England_not_london']:
    polls_17[geo] = polls_17[geo] / polls_17[geo].sum()

In [27]:
# Let's take a look!
polls_17

{'UK': con      0.422770
 lab      0.369010
 ld       0.070021
 ukip     0.041297
 snp      0.038675
 grn      0.019022
 pc       0.009441
 other    0.029763
 dtype: float64, 'Scotland': con      0.271401
 lab      0.236513
 ld       0.053923
 ukip     0.003895
 snp      0.418192
 grn      0.010513
 pc       0.000000
 other    0.005563
 dtype: float64, 'Wales': con      0.314166
 lab      0.430377
 ld       0.044139
 ukip     0.045792
 pc       0.148997
 grn      0.000783
 snp      0.000000
 other    0.015746
 dtype: float64, 'NI': grn      0.006
 ukip     0.001
 con      0.002
 lab          0
 ld           0
 snp          0
 pc           0
 other    0.991
 Name: 5, dtype: object, 'London': con      0.376424
 lab      0.458455
 ld       0.104133
 ukip     0.031145
 grn      0.021655
 snp      0.000000
 pc       0.000000
 other    0.008189
 dtype: float64, 'England_not_london': con      0.473778
 grn      0.021718
 lab      0.375500
 ld       0.070441
 pc       0.000000
 snp      0.000000
 ukip     0.048529
 other    0.010034
 dtype: float64}

## Export polling data

In [28]:
polls_15_csv = pd.DataFrame(columns=['con', 'lab', 'ld', 'ukip', 'grn', 'snp', 'pc', 'other'])
for geo in polls:
    for party in polls[geo].index:
        polls_15_csv.loc[geo, party] = polls[geo].loc[party]
polls_15_csv.to_csv(polls_data_dir / 'final_polls_2015.csv', index=True)
polls_15_csv

         con       lab    ld      ukip        grn  snp   pc      other
UK  0.338182  0.337273  0.09  0.127273  0.0481818  NaN  NaN  0.0590909

In [29]:
polls_17_csv = pd.DataFrame(columns=['con', 'lab', 'ld', 'ukip', 'grn', 'snp', 'pc', 'other'])
for geo in polls_17:
    for party in polls_17[geo].index:
        polls_17_csv.loc[geo, party] = polls_17[geo].loc[party]
polls_17_csv.to_csv(polls_data_dir / 'final_polls_2017.csv', index=True)
polls_17_csv

,con,lab,ld,ukip,grn,snp,pc,other
UK,0.42277,0.36901,0.0700214,0.041297,0.0190216,0.0386751,0.00944149,0.0297635
Scotland,0.271401,0.236513,0.0539225,0.00389513,0.0105126,0.418192,0,0.0055632
Wales,0.314166,0.430377,0.0441389,0.0457916,0.000782789,0,0.148997,0.015746
NI,0.002,0,0,0.001,0.006,0,0,0.991
London,0.376424,0.458455,0.104133,0.0311447,0.0216548,0,0,0.00818921
England_not_london,0.473778,0.3755,0.0704406,0.0485293,0.0217184,0,0,0.0100342

## Reduce ge_2010 dataframe to above results only

In [30]:
# GE 2010 dataset has a lot of parties...
ge_2010.head()

,Press Association Reference,Constituency Name,Region,Election Year,Electorate,Votes,AC,AD,AGS,APNI,APP,AWL,AWP,BB,BCP,Bean,Best,BGPV,BIB,BIC,Blue,BNP,BP Elvis,C28,Cam Soc,CG,Ch M,Ch P,CIP,CITY,CNPG,Comm,Comm L,Con,Cor D,CPA,CSP,CTDP,CURE,D Lab,D Nat,DDP,DUP,ED,EIP,EPA,FAWG,FDP,FFR,Grn,GSOT,Hum,ICHC,IEAC,IFED,ILEU,Impact,Ind1,Ind2,Ind3,Ind4,Ind5,IPT,ISGB,ISQM,IUK,IVH,IZB,JAC,Joy,JP,Lab,Land,LD,Lib,Libert,LIND,LLPB,LTT,MACI,MCP,MEDI,MEP,MIF,MK,MPEA,MRLP,MRP,Nat Lib,NCDV,ND,New,NF,NFP,NICF,Nobody,NSPS,PBP,PC,Pirate,PNDP,Poet,PPBF,PPE,PPNV,Reform,Respect,Rest,RRG,RTBP,SACL,Sci,SDLP,SEP,SF,SIG,SJP,SKGP,SMA,SMRA,SNP,Soc,Soc Alt,Soc Dem,Soc Lab,South,Speaker,SSP,TF,TOC,Trust,TUSC,TUV,UCUNF,UKIP,UPS,UV,VCCA,Vote,Wessex Reg,WRP,You,Youth,YRDPL
0,1.0,Aberavon,Wales,2010.0,50838.0,30958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,558.0,0.0,0.0,0.0,0.0,0.0,1276.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4411.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,919.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16073.0,0.0,5034.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2198.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,Aberconwy,Wales,2010.0,44593.0,29966,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.0,0.0,0.0,0.0,0.0,0.0,10734.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7336.0,0.0,5786.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5341.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,632.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,Aberdeen North,Scotland,2010.0,64808.0,37701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,635.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16746.0,0.0,7001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8385.0,0.0,0.0,0.0,0.0,0.0,0.0,268.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.0,Aberdeen South,Scotland,2010.0,64031.0,43034,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,529.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8914.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,413.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15722.0,0.0,12216.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5102.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,Aberdeenshire West & Kincardine,Scotland,2010.0,66110.0,45195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,513.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13678.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6159.0,0.0,17362.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7086.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,397.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
# Top 15 parties
ge_2010.iloc[:, 11:].sum().sort_values(ascending=False).head(15)

Con        10703654.0
Lab         8606517.0
LD          6836248.0
UKIP         919471.0
BNP          564321.0
SNP          491386.0
Grn          285612.0
Ind1         175604.0
SF           171942.0
DUP          168216.0
PC           165394.0
SDLP         110970.0
UCUNF        102361.0
ED            64826.0
Respect       33251.0
dtype: float64

In [32]:
# Define other parties
other_parties = list(set(ge_2010.columns) - set(ge_2010.columns[:6]) - set(parties_lookup_2010.keys()))
other_parties_2015 = list(set(ge_2015.columns) - set(ge_2015.columns[:11]) - set(parties_lookup_2015.keys()))

ge_2010['Other'] = ge_2010.loc[:, other_parties].sum(axis=1)
ge_2015['Other'] = ge_2015.loc[:, other_parties_2015].sum(axis=1)

### # Export somewhat cleaned up 2010/2015 results data

In [33]:
# It looks like this
ge_2010.head(3)

,Press Association Reference,Constituency Name,Region,Election Year,Electorate,Votes,AC,AD,AGS,APNI,APP,AWL,AWP,BB,BCP,Bean,Best,BGPV,BIB,BIC,Blue,BNP,BP Elvis,C28,Cam Soc,CG,Ch M,Ch P,CIP,CITY,CNPG,Comm,Comm L,Con,Cor D,CPA,CSP,CTDP,CURE,D Lab,D Nat,DDP,DUP,ED,EIP,EPA,FAWG,FDP,FFR,Grn,GSOT,Hum,ICHC,IEAC,IFED,ILEU,Impact,Ind1,Ind2,Ind3,Ind4,Ind5,IPT,ISGB,ISQM,IUK,IVH,IZB,JAC,Joy,JP,Lab,Land,LD,Lib,Libert,LIND,LLPB,LTT,MACI,MCP,MEDI,MEP,MIF,MK,MPEA,MRLP,MRP,Nat Lib,NCDV,ND,New,NF,NFP,NICF,Nobody,NSPS,PBP,PC,Pirate,PNDP,Poet,PPBF,PPE,PPNV,Reform,Respect,Rest,RRG,RTBP,SACL,Sci,SDLP,SEP,SF,SIG,SJP,SKGP,SMA,SMRA,SNP,Soc,Soc Alt,Soc Dem,Soc Lab,South,Speaker,SSP,TF,TOC,Trust,TUSC,TUV,UCUNF,UKIP,UPS,UV,VCCA,Vote,Wessex Reg,WRP,You,Youth,YRDPL,Other
0,1.0,Aberavon,Wales,2010.0,50838.0,30958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,558.0,0.0,0.0,0.0,0.0,0.0,1276.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4411.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,919.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16073.0,0.0,5034.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2198.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4951.0
1,2.0,Aberconwy,Wales,2010.0,44593.0,29966,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.0,0.0,0.0,0.0,0.0,0.0,10734.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7336.0,0.0,5786.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5341.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,632.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5478.0
2,3.0,Aberdeen North,Scotland,2010.0,64808.0,37701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,635.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16746.0,0.0,7001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8385.0,0.0,0.0,0.0,0.0,0.0,0.0,268.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9288.0

In [34]:
# Export to disk
ge_2010.to_csv(DATA_DIR / 'model' / 'ge10_all_parties.csv', index=False)
ge_2010.to_feather(DATA_DIR / 'model' / 'ge10_all_parties.feather')

ge_2015.to_csv(DATA_DIR / 'model' / 'ge15_all_parties.csv', index=False)
ge_2015.to_feather(DATA_DIR / 'model' / 'ge15_all_parties.feather')

### Rename for convenience

In [35]:
ge_2010_full = ge_2010.copy()
ge_2015_full = ge_2015.copy()

### Filter to metadata cols + parties of interest

In [36]:
parties_15 = ['con', 'lab', 'ld', 'ukip', 'grn', 'other']
parties_17 = ['con', 'lab', 'ld', 'ukip', 'grn', 'snp', 'pc', 'other']

parties_lookup_2010 = {
    'Con': 'con',
    'Lab': 'lab',
    'LD': 'ld',
    'UKIP': 'ukip',
    'Grn': 'grn',
    'Other': 'other'
}

parties_lookup_2015 = {
    'C': 'con',
    'Lab': 'lab',
    'LD': 'ld',
    'UKIP': 'ukip',
    'Green': 'grn',
    'SNP': 'snp',
    'PC': 'pc',
    'Other': 'other'
}

In [37]:
# Filter ge to metadata cols + parties of interest
ge_2010 = ge_2010.loc[:, list(ge_2010.columns[:6]) + list(parties_lookup_2010.keys())]
ge_2015 = ge_2015.loc[:, list(ge_2015.columns[:11]) + list(parties_lookup_2015.keys())]

# Rename parties
ge_2010.columns = [parties_lookup_2010[x] if x in parties_lookup_2010 else x for x in ge_2010.columns]
ge_2015.columns = [parties_lookup_2015[x] if x in parties_lookup_2015 else x for x in ge_2015.columns]

# Calculate vote share
for party in parties_15:
    ge_2010[party + '_pc'] = ge_2010[party] / ge_2010['Votes']

for party in parties_17:
    ge_2015[party + '_pc'] = ge_2015[party] / ge_2015['Valid Votes']

ge_2010.head(3)

,Press Association Reference,Constituency Name,Region,Election Year,Electorate,Votes,con,lab,ld,ukip,grn,other,con_pc,lab_pc,ld_pc,ukip_pc,grn_pc,other_pc
0,1.0,Aberavon,Wales,2010.0,50838.0,30958,4411.0,16073.0,5034.0,489.0,0.0,4951.0,0.142483,0.519187,0.162607,0.015796,0.0,0.159926
1,2.0,Aberconwy,Wales,2010.0,44593.0,29966,10734.0,7336.0,5786.0,632.0,0.0,5478.0,0.358206,0.244811,0.193085,0.021091,0.0,0.182807
2,3.0,Aberdeen North,Scotland,2010.0,64808.0,37701,4666.0,16746.0,7001.0,0.0,0.0,9288.0,0.123763,0.444179,0.185698,0.000000,0.0,0.246360

In [38]:
# Export to disk
ge_2010.to_csv(DATA_DIR / 'model' / 'ge10.csv', index=False)
ge_2010.to_feather(DATA_DIR / 'model' / 'ge10.feather')

ge_2015.to_csv(DATA_DIR / 'model' / 'ge15.csv', index=False)
ge_2015.to_feather(DATA_DIR / 'model' / 'ge15.feather')

### Calculate uplifts ("swing")

In [39]:
# Calculate national voteshare in 2010
ge_2010_totals = ge_2010.loc[:, ['Votes'] + parties_15].sum()
ge_2010_voteshare = ge_2010_totals / ge_2010_totals['Votes']
del ge_2010_voteshare['Votes']
ge_2010_voteshare

con      0.360543
lab      0.289903
ld       0.230273
ukip     0.030972
grn      0.009621
other    0.078689
dtype: float64

In [40]:
# Calculate swing between 2015 and latest smoothed polling
swing = ge_2010_voteshare.copy()
for party in parties_15:
    swing[party] = polls_15_csv.loc['UK', party] / ge_2010_voteshare[party] - 1
    ge_2010[party + '_swing'] = polls_15_csv.loc['UK', party] / ge_2010_voteshare[party] - 1
swing

con     -0.062021
lab      0.163400
ld      -0.609159
ukip     3.109344
grn      4.008203
other   -0.249062
dtype: float64

In [41]:
# Forecast is previous result multiplied by swing uplift
for party in parties_15:
    ge_2010[party + '_forecast'] = ge_2010[party + '_pc'] * (1 + swing[party])

In [42]:
def win_10(row):
    all_parties = set(ge_2010_full.columns[6:]) - set(['Other'])
    out = row[all_parties].sort_values(ascending=False).index[0]
    if out in parties_lookup_2010.keys():
        out = parties_lookup_2010[out]
    elif out == 'Speaker':
        out = 'other'
    return out

def win_15(row):
    all_parties = set(ge_2015_full.columns[11:]) - set(['Other'])
    out = row[all_parties].sort_values(ascending=False).index[0]
    if out in parties_lookup_2015.keys():
        out = parties_lookup_2015[out]
    elif out == 'Speaker':
        out = 'other'
    return out

In [43]:
def pred_15(row):
    return row[[p + '_forecast' for p in parties_15]].sort_values(ascending=False).index[0].replace('_forecast', '')

In [44]:
ge_2010['win_10'] = ge_2010_full.apply(win_10, axis=1)
ge_2015['win_15'] = ge_2015_full.apply(win_15, axis=1)

In [45]:
ge_2010['win_15'] = ge_2010.apply(pred_15, axis=1)

In [46]:
ge_2010.groupby('win_10').count()['Constituency Name'].sort_values(ascending=False)

win_10
con      306
lab      258
ld        57
DUP        8
SNP        6
SF         5
SDLP       3
PC         3
other      1
grn        1
Ind1       1
APNI       1
Name: Constituency Name, dtype: int64

In [47]:
ge_2010.groupby('win_15').count()['Constituency Name'].sort_values(ascending=False)

win_15
lab      325
con      294
other     25
grn        3
ukip       2
ld         1
Name: Constituency Name, dtype: int64

In [48]:
ge_2015.groupby('win_15').count()['Constituency Name'].sort_values(ascending=False)

win_15
con      330
lab      232
snp       56
ld         8
DUP        8
SF         4
pc         3
SDLP       3
UUP        2
ukip       1
other      1
grn        1
Ind        1
Name: Constituency Name, dtype: int64

### Calculate Geo-Level Voteshare + Swing inc. all parties

In [49]:
# Add geos
ge_2015['geo'] = ge_2015['Press Association ID Number'].map(geo_lookup)
geos = list(ge_2015.geo.unique())

In [50]:
# Calculate geo-level voteshare in 2015
ge_2015_totals = ge_2015.loc[:, ['Valid Votes', 'geo'] + parties_17].groupby('geo').sum()
ge_2015_totals

,Valid Votes,con,lab,ld,ukip,grn,snp,pc,other
geo,,,,,,,,,
England_not_london,22034643.0,9215258.0,6542605.0,1825914.0,3324386.0,901589.0,0.0,0.0,224891.0
London,3536251.0,1233386.0,1545048.0,272544.0,286981.0,171670.0,0.0,0.0,26622.0
NI,718103.0,9055.0,0.0,0.0,18324.0,6822.0,0.0,0.0,683902.0
Scotland,2910465.0,434097.0,707147.0,219675.0,47078.0,39205.0,1454436.0,0.0,8827.0
Wales,1498063.0,407813.0,552473.0,97783.0,204330.0,38344.0,0.0,181704.0,15616.0

In [51]:
# Convert into vote share
ge_2015_voteshare = ge_2015_totals.div(ge_2015_totals['Valid Votes'], axis=0)
del ge_2015_voteshare['Valid Votes']
ge_2015_voteshare

,con,lab,ld,ukip,grn,snp,pc,other
geo,,,,,,,,
England_not_london,0.418217,0.296924,0.082866,0.150871,0.040917,0.000000,0.000000,0.010206
London,0.348783,0.436917,0.077071,0.081154,0.048546,0.000000,0.000000,0.007528
NI,0.012610,0.000000,0.000000,0.025517,0.009500,0.000000,0.000000,0.952373
Scotland,0.149150,0.242967,0.075478,0.016175,0.013470,0.499726,0.000000,0.003033
Wales,0.272227,0.368792,0.065273,0.136396,0.025596,0.000000,0.121293,0.010424

In [52]:
# Calculate geo-swing
swing_17 = ge_2015_voteshare.copy()
for party in parties_17:
    for geo in geos:
        if ge_2015_voteshare.loc[geo][party] > 0:
            out = polls_17[geo][party] / ge_2015_voteshare.loc[geo][party] - 1
        else:
            out = 0.0
        swing_17.loc[geo, party] = out

swing_17

,con,lab,ld,ukip,grn,snp,pc,other
geo,,,,,,,,
England_not_london,0.132852,0.264635,-0.149941,-0.678339,-0.469206,0.000000,0.000000,-0.016859
London,0.079248,0.049295,0.351117,-0.616227,-0.553930,0.000000,0.000000,0.087788
NI,-0.841391,0.000000,0.000000,-0.960811,-0.368423,0.000000,0.000000,0.040559
Scotland,0.819646,-0.026562,-0.285583,-0.759194,-0.219572,-0.163158,0.000000,0.834316
Wales,0.154059,0.166994,-0.323779,-0.664275,-0.969417,0.000000,0.228413,0.510532

In [53]:
# Apply swing
for party in parties_17:
    ge_2015[party + '_swing'] = ge_2015.apply(lambda row: swing_17.loc[row['geo']][party], axis=1)
    ge_2015[party + '_2017_forecast'] = ge_2015.apply(lambda x: x[party + '_pc'] * (1 + swing_17.loc[x['geo']][party]), axis=1)

In [54]:
ge_2015.groupby('win_15').count()['Constituency Name'].sort_values(ascending=False)

win_15
con      330
lab      232
snp       56
ld         8
DUP        8
SF         4
pc         3
SDLP       3
UUP        2
ukip       1
other      1
grn        1
Ind        1
Name: Constituency Name, dtype: int64

In [55]:
def win_17(row):
    return row[[p + '_2017_forecast' for p in parties_17]].sort_values(ascending=False).index[0].replace('_2017_forecast', '')

In [56]:
ge_2015['win_17'] = ge_2015.apply(win_17, axis=1)

In [57]:
ge_2015.groupby('win_17').count()['Constituency Name'].sort_values(ascending=False)

win_17
con      329
lab      245
snp       46
other     19
ld         6
pc         5
Name: Constituency Name, dtype: int64

### Turn into ML-ready dataset

In [58]:
parties = ['con', 'lab', 'ld', 'ukip', 'grn']

In [59]:
act_15_lookup = {k: v for i, (k, v) in ge_2015[['Press Association ID Number', 'win_15']].iterrows()}
ge_2010['act_15'] = ge_2010['Press Association Reference'].map(act_15_lookup)

In [60]:
pc_15_lookup = {
    p: {k: v for i, (k, v) in ge_2015[['Press Association ID Number', p + '_pc']].iterrows()} for p in parties
}

In [61]:
for p in parties:
    ge_2010[p + '_actual'] = ge_2010['Press Association Reference'].map(pc_15_lookup[p])

### Melt into following cols:
- 'Press Association Reference'
- 'Constituency Name'
- 'Region'
- 'Electorate'
- 'Votes'
- 'party'
- 'votes_last'
- 'pc_last'
- 'win_last'
- 'polls_now'
- 'swing_now'
- 'swing_forecast_pc'
- 'swing_forecast_win'
- 'actual_win_now'
- 'actual_pc_now'

In [62]:
df = ge_2010[['Press Association Reference', 'Constituency Name', 'Region', 'Electorate', 'Votes'] + parties]
df.head()

,Press Association Reference,Constituency Name,Region,Electorate,Votes,con,lab,ld,ukip,grn
0,1.0,Aberavon,Wales,50838.0,30958,4411.0,16073.0,5034.0,489.0,0.0
1,2.0,Aberconwy,Wales,44593.0,29966,10734.0,7336.0,5786.0,632.0,0.0
2,3.0,Aberdeen North,Scotland,64808.0,37701,4666.0,16746.0,7001.0,0.0,0.0
3,4.0,Aberdeen South,Scotland,64031.0,43034,8914.0,15722.0,12216.0,0.0,413.0
4,5.0,Aberdeenshire West & Kincardine,Scotland,66110.0,45195,13678.0,6159.0,17362.0,397.0,0.0

In [63]:
df.shape

(650, 10)

In [64]:
df = pd.melt(
    df,
    id_vars=['Press Association Reference', 'Constituency Name', 'Region', 'Electorate', 'Votes'],
    value_vars=parties,
    var_name='party',
    value_name='votes_last'
)

In [65]:
df.shape

(3250, 7)

In [66]:
# pc_last

In [67]:
pc_last = pd.melt(
    ge_2010[['Press Association Reference'] + [p + '_pc' for p in parties]],
    id_vars=['Press Association Reference'],
    value_vars=[p + '_pc' for p in parties],
    var_name='party',
    value_name='pc_last'
)
pc_last['party'] = pc_last.party.apply(lambda x: x.replace('_pc', ''))

In [68]:
df = pd.merge(
    left=df,
    right=pc_last,
    how='left',
    on=['Press Association Reference', 'party']
)

In [69]:
df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483
1,2.0,Aberconwy,Wales,44593.0,29966,con,10734.0,0.358206
2,3.0,Aberdeen North,Scotland,64808.0,37701,con,4666.0,0.123763

In [70]:
# win_last

In [71]:
win_last = ge_2010[['Press Association Reference', 'win_10']]
win_last.columns = ['Press Association Reference', 'win_last']
df = pd.merge(
    left=df,
    right=win_last,
    on=['Press Association Reference']
)

In [72]:
df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab

In [73]:
# polls_now
df['polls_now'] = df.party.map(polls['UK'])
df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000

In [74]:
# swing_now
swing_now = pd.melt(
    ge_2010[['Press Association Reference'] + [p + '_swing' for p in parties]],
    id_vars=['Press Association Reference'],
    value_vars=[p + '_swing' for p in parties],
    var_name='party',
    value_name='swing_now'
)
swing_now['party'] = swing_now.party.apply(lambda x: x.replace('_swing', ''))

df = pd.merge(
    left=df,
    right=swing_now,
    how='left',
    on=['Press Association Reference', 'party']
)
df.head(10)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182,-0.062021
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273,0.163400
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000,-0.609159
3,1.0,Aberavon,Wales,50838.0,30958,ukip,489.0,0.015796,lab,0.127273,3.109344
4,1.0,Aberavon,Wales,50838.0,30958,grn,0.0,0.000000,lab,0.048182,4.008203
5,2.0,Aberconwy,Wales,44593.0,29966,con,10734.0,0.358206,con,0.338182,-0.062021
6,2.0,Aberconwy,Wales,44593.0,29966,lab,7336.0,0.244811,con,0.337273,0.163400
7,2.0,Aberconwy,Wales,44593.0,29966,ld,5786.0,0.193085,con,0.090000,-0.609159
8,2.0,Aberconwy,Wales,44593.0,29966,ukip,632.0,0.021091,con,0.127273,3.109344
9,2.0,Aberconwy,Wales,44593.0,29966,grn,0.0,0.000000,con,0.048182,4.008203

In [75]:
# swing_forecast_pc
swing_forecast_pc = pd.melt(
    ge_2010[['Press Association Reference'] + [p + '_forecast' for p in parties]],
    id_vars=['Press Association Reference'],
    value_vars=[p + '_forecast' for p in parties],
    var_name='party',
    value_name='swing_forecast_pc'
)
swing_forecast_pc['party'] = swing_forecast_pc.party.apply(lambda x: x.replace('_forecast', ''))

df = pd.merge(
    left=df,
    right=swing_forecast_pc,
    how='left',
    on=['Press Association Reference', 'party']
)

In [76]:
df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now,swing_forecast_pc
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182,-0.062021,0.133646
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273,0.163400,0.604022
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000,-0.609159,0.063554

In [77]:
# swing_forecast_win
swing_forecast_win = ge_2010[['Press Association Reference', 'win_15']]
swing_forecast_win.columns = ['Press Association Reference', 'swing_forecast_win']
df = pd.merge(
    left=df,
    right=swing_forecast_win,
    on=['Press Association Reference']
)

In [78]:
df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now,swing_forecast_pc,swing_forecast_win
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182,-0.062021,0.133646,lab
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273,0.163400,0.604022,lab
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000,-0.609159,0.063554,lab

In [79]:
# actual_win_now
actual_win_now = ge_2010[['Press Association Reference', 'act_15']]
actual_win_now.columns = ['Press Association Reference', 'actual_win_now']
df = pd.merge(
    left=df,
    right=actual_win_now,
    on=['Press Association Reference']
)
df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now,swing_forecast_pc,swing_forecast_win,actual_win_now
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182,-0.062021,0.133646,lab,lab
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273,0.163400,0.604022,lab,lab
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000,-0.609159,0.063554,lab,lab

In [80]:
# actual_pc_now
actual_pc_now = pd.melt(
    ge_2010[['Press Association Reference'] + [p + '_actual' for p in parties]],
    id_vars=['Press Association Reference'],
    value_vars=[p + '_actual' for p in parties],
    var_name='party',
    value_name='actual_pc_now'
)
actual_pc_now['party'] = actual_pc_now.party.apply(lambda x: x.replace('_actual', ''))

df = pd.merge(
    left=df,
    right=actual_pc_now,
    how='left',
    on=['Press Association Reference', 'party']
)

In [81]:
df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now,swing_forecast_pc,swing_forecast_win,actual_win_now,actual_pc_now
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182,-0.062021,0.133646,lab,lab,0.118707
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273,0.163400,0.604022,lab,lab,0.489040
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000,-0.609159,0.063554,lab,lab,0.044317

In [82]:
# dummy party
df = pd.concat([df, pd.get_dummies(df.party)], axis=1)

# dummy region
df = pd.concat([df, pd.get_dummies(df.Region, prefix='Region')], axis=1)

df.head(3)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now,swing_forecast_pc,swing_forecast_win,actual_win_now,actual_pc_now,con,grn,lab,ld,ukip,Region_East Midlands,Region_Eastern,Region_London,Region_North East,Region_North West,Region_Northern Ireland,Region_Scotland,Region_South East,Region_South West,Region_Wales,Region_West Midlands,Region_Yorkshire and the Humber
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182,-0.062021,0.133646,lab,lab,0.118707,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273,0.163400,0.604022,lab,lab,0.489040,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000,-0.609159,0.063554,lab,lab,0.044317,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0

In [83]:
# won_here_last
df['won_here_last'] = (df['party'] == df['win_last']).astype('int')

In [84]:
df.head(20)

,Press Association Reference,Constituency Name,Region,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now,swing_forecast_pc,swing_forecast_win,actual_win_now,actual_pc_now,con,grn,lab,ld,ukip,Region_East Midlands,Region_Eastern,Region_London,Region_North East,Region_North West,Region_Northern Ireland,Region_Scotland,Region_South East,Region_South West,Region_Wales,Region_West Midlands,Region_Yorkshire and the Humber,won_here_last
0,1.0,Aberavon,Wales,50838.0,30958,con,4411.0,0.142483,lab,0.338182,-0.062021,0.133646,lab,lab,0.118707,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,1.0,Aberavon,Wales,50838.0,30958,lab,16073.0,0.519187,lab,0.337273,0.163400,0.604022,lab,lab,0.489040,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
2,1.0,Aberavon,Wales,50838.0,30958,ld,5034.0,0.162607,lab,0.090000,-0.609159,0.063554,lab,lab,0.044317,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,1.0,Aberavon,Wales,50838.0,30958,ukip,489.0,0.015796,lab,0.127273,3.109344,0.064910,lab,lab,0.157694,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
4,1.0,Aberavon,Wales,50838.0,30958,grn,0.0,0.000000,lab,0.048182,4.008203,0.000000,lab,lab,0.022555,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,2.0,Aberconwy,Wales,44593.0,29966,con,10734.0,0.358206,con,0.338182,-0.062021,0.335990,con,con,0.415052,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
6,2.0,Aberconwy,Wales,44593.0,29966,lab,7336.0,0.244811,con,0.337273,0.163400,0.284813,con,con,0.282407,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
7,2.0,Aberconwy,Wales,44593.0,29966,ld,5786.0,0.193085,con,0.090000,-0.609159,0.075466,con,con,0.046139,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
8,2.0,Aberconwy,Wales,44593.0,29966,ukip,632.0,0.021091,con,0.127273,3.109344,0.086668,con,con,0.114999,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
9,2.0,Aberconwy,Wales,44593.0,29966,grn,0.0,0.000000,con,0.048182,4.008203,0.000000,con,con,0.024114,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,3.0,Aberdeen North,Scotland,64808.0,37701,con,4666.0,0.123763,lab,0.338182,-0.062021,0.116087,lab,snp,0.120721,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
11,3.0,Aberdeen North,Scotland,64808.0,37701,lab,16746.0,0.444179,lab,0.337273,0.163400,0.516758,lab,snp,0.259400,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
12,3.0,Aberdeen North,Scotland,64808.0,37701,ld,7001.0,0.185698,lab,0.090000,-0.609159,0.072578,lab,snp,0.046659,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
13,3.0,Aberdeen North,Scotland,64808.0,37701,ukip,0.0,0.000000,lab,0.127273,3.109344,0.000000,lab,snp,0.000000,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
14,3.0,Aberdeen North,Scotland,64808.0,37701,grn,0.0,0.000000,lab,0.048182,4.008203,0.000000,lab,snp,0.000000,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
15,4.0,Aberdeen South,Scotland,64031.0,43034,con,8914.0,0.207139,lab,0.338182,-0.062021,0.194292,lab,snp,0.228358,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
16,4.0,Aberdeen South,Scotland,64031.0,43034,lab,15722.0,0.365339,lab,0.337273,0.163400,0.425035,lab,snp,0.267574,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
17,4.0,Aberdeen South,Scotland,64031.0,43034,ld,12216.0,0.283869,lab,0.090000,-0.609159,0.110947,lab,snp,0.046384,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
18,4.0,Aberdeen South,Scotland,64031.0,43034,ukip,0.0,0.000000,lab,0.127273,3.109344,0.000000,lab,snp,0.018475,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
19,4.0,Aberdeen South,Scotland,64031.0,43034,grn,413.0,0.009597,lab,0.048182,4.008203,0.048064,lab,snp,0.019855,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

### Export final 2010 -> 2015 training set

In [85]:
df.to_csv(DATA_DIR / 'model' / 'ge_2010_2015_training_data.csv', index=False)
df.to_feather(DATA_DIR / 'model' / 'ge_2010_2015_training_data.feather')

### Recreate this training dataset using same column names for 2015 -> 2017 for a GE2017 forecast
This would be much simpler with a bit of refactoring! Anyone interested in helping out please get in touch with @john_sandall, happy to give free mentoring in return for collaborating on this work!

### Melt into following cols:
- 'Press Association Reference'
- 'Constituency Name'
- 'Region'
- 'Electorate'
- 'Votes'
- 'party'
- 'votes_last'
- 'pc_last'
- 'win_last'
- 'polls_now'
- 'swing_now'
- 'swing_forecast_pc'
- 'swing_forecast_win'

In [87]:
# Add SNP and Plaid Cymru
parties += ['snp', 'pc']
parties

['con', 'lab', 'ld', 'ukip', 'grn', 'snp', 'pc']

In [88]:
df15 = ge_2015[['Press Association ID Number', 'Constituency Name', 'Region', 'geo', 'Electorate', 'Valid Votes'] + parties]
df15.columns = ['Press Association ID Number', 'Constituency Name', 'Region', 'geo', 'Electorate', 'Votes'] + parties
df15.head()

,Press Association ID Number,Constituency Name,Region,geo,Electorate,Votes,con,lab,ld,ukip,grn,snp,pc
0,1.0,Aberavon,Wales,Wales,49821.0,31523.0,3742.0,15416.0,1397.0,4971.0,711.0,0.0,3663.0
1,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,12513.0,8514.0,1391.0,3467.0,727.0,0.0,3536.0
2,3.0,Aberdeen North,Scotland,Scotland,67745.0,43936.0,5304.0,11397.0,2050.0,0.0,0.0,24793.0,0.0
3,4.0,Aberdeen South,Scotland,Scotland,68056.0,48551.0,11087.0,12991.0,2252.0,897.0,964.0,20221.0,0.0
4,5.0,Aberdeenshire West & Kincardine,Scotland,Scotland,73445.0,55196.0,15916.0,2487.0,11812.0,1006.0,885.0,22949.0,0.0

In [89]:
df15.shape

(650, 13)

In [90]:
df15 = pd.melt(
    df15,
    id_vars=['Press Association ID Number', 'Constituency Name', 'Region', 'geo', 'Electorate', 'Votes'],
    value_vars=parties,
    var_name='party',
    value_name='votes_last'
)

In [91]:
df15.shape

(4550, 8)

In [93]:
# pc_last
pc_last = pd.melt(
    ge_2015[['Press Association ID Number'] + [p + '_pc' for p in parties]],
    id_vars=['Press Association ID Number'],
    value_vars=[p + '_pc' for p in parties],
    var_name='party',
    value_name='pc_last'
)
pc_last['party'] = pc_last.party.apply(lambda x: x.replace('_pc', ''))

In [94]:
df15 = pd.merge(
    left=df15,
    right=pc_last,
    how='left',
    on=['Press Association ID Number', 'party']
)

In [95]:
# win_last
win_last = ge_2015[['Press Association ID Number', 'win_15']]
win_last.columns = ['Press Association ID Number', 'win_last']
df15 = pd.merge(
    left=df15,
    right=win_last,
    on=['Press Association ID Number']
)

In [96]:
# polls_now <- USE REGIONAL POLLING! (Possibly a very bad idea, the regional UNS performed worse than national!)
df15['polls_now'] = df15.apply(lambda row: polls_17[row.geo][row.party], axis=1)

In [97]:
# swing_now
swing_now = pd.melt(
    ge_2015[['Press Association ID Number'] + [p + '_swing' for p in parties]],
    id_vars=['Press Association ID Number'],
    value_vars=[p + '_swing' for p in parties],
    var_name='party',
    value_name='swing_now'
)
swing_now['party'] = swing_now.party.apply(lambda x: x.replace('_swing', ''))

df15 = pd.merge(
    left=df15,
    right=swing_now,
    how='left',
    on=['Press Association ID Number', 'party']
)

In [98]:
# swing_forecast_pc
swing_forecast_pc = pd.melt(
    ge_2015[['Press Association ID Number'] + [p + '_2017_forecast' for p in parties]],
    id_vars=['Press Association ID Number'],
    value_vars=[p + '_2017_forecast' for p in parties],
    var_name='party',
    value_name='swing_forecast_pc'
)
swing_forecast_pc['party'] = swing_forecast_pc.party.apply(lambda x: x.replace('_2017_forecast', ''))

df15 = pd.merge(
    left=df15,
    right=swing_forecast_pc,
    how='left',
    on=['Press Association ID Number', 'party']
)

In [99]:
# swing_forecast_win
swing_forecast_win = ge_2015[['Press Association ID Number', 'win_17']]
swing_forecast_win.columns = ['Press Association ID Number', 'swing_forecast_win']
df15 = pd.merge(
    left=df15,
    right=swing_forecast_win,
    on=['Press Association ID Number']
)

In [100]:
# dummy party
df15 = pd.concat([df15, pd.get_dummies(df15.party)], axis=1)

In [101]:
# dummy region
df15 = pd.concat([df15, pd.get_dummies(df15.Region, prefix='Region')], axis=1)

In [102]:
# won_here_last
df15['won_here_last'] = (df15['party'] == df15['win_last']).astype('int')

In [103]:
df15.head(20)

,Press Association ID Number,Constituency Name,Region,geo,Electorate,Votes,party,votes_last,pc_last,win_last,polls_now,swing_now,swing_forecast_pc,swing_forecast_win,con,grn,lab,ld,pc,snp,ukip,Region_East,Region_East Midlands,Region_London,Region_North East,Region_North West,Region_Northern Ireland,Region_Scotland,Region_South East,Region_South West,Region_Wales,Region_West Midlands,Region_Yorkshire and The Humber,won_here_last
0,1.0,Aberavon,Wales,Wales,49821.0,31523.0,con,3742.0,0.118707,lab,0.314166,0.154059,0.136995,lab,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,1.0,Aberavon,Wales,Wales,49821.0,31523.0,lab,15416.0,0.489040,lab,0.430377,0.166994,0.570706,lab,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
2,1.0,Aberavon,Wales,Wales,49821.0,31523.0,ld,1397.0,0.044317,lab,0.044139,-0.323779,0.029968,lab,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,1.0,Aberavon,Wales,Wales,49821.0,31523.0,ukip,4971.0,0.157694,lab,0.045792,-0.664275,0.052942,lab,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
4,1.0,Aberavon,Wales,Wales,49821.0,31523.0,grn,711.0,0.022555,lab,0.000783,-0.969417,0.000690,lab,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,1.0,Aberavon,Wales,Wales,49821.0,31523.0,snp,0.0,0.000000,lab,0.000000,0.000000,0.000000,lab,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
6,1.0,Aberavon,Wales,Wales,49821.0,31523.0,pc,3663.0,0.116201,lab,0.148997,0.228413,0.142743,lab,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
7,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,con,12513.0,0.415052,con,0.314166,0.154059,0.478995,con,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
8,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,lab,8514.0,0.282407,con,0.430377,0.166994,0.329567,con,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
9,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,ld,1391.0,0.046139,con,0.044139,-0.323779,0.031200,con,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,ukip,3467.0,0.114999,con,0.045792,-0.664275,0.038608,con,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
11,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,grn,727.0,0.024114,con,0.000783,-0.969417,0.000737,con,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,snp,0.0,0.000000,con,0.000000,0.000000,0.000000,con,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
13,2.0,Aberconwy,Wales,Wales,45525.0,30148.0,pc,3536.0,0.117288,con,0.148997,0.228413,0.144078,con,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
14,3.0,Aberdeen North,Scotland,Scotland,67745.0,43936.0,con,5304.0,0.120721,snp,0.271401,0.819646,0.219670,snp,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
15,3.0,Aberdeen North,Scotland,Scotland,67745.0,43936.0,lab,11397.0,0.259400,snp,0.236513,-0.026562,0.252510,snp,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
16,3.0,Aberdeen North,Scotland,Scotland,67745.0,43936.0,ld,2050.0,0.046659,snp,0.053923,-0.285583,0.033334,snp,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
17,3.0,Aberdeen North,Scotland,Scotland,67745.0,43936.0,ukip,0.0,0.000000,snp,0.003895,-0.759194,0.000000,snp,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
18,3.0,Aberdeen North,Scotland,Scotland,67745.0,43936.0,grn,0.0,0.000000,snp,0.010513,-0.219572,0.000000,snp,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
19,3.0,Aberdeen North,Scotland,Scotland,67745.0,43936.0,snp,24793.0,0.564298,snp,0.418192,-0.163158,0.472229,snp,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1

### Export final 2015 -> 2017 prediction set

In [104]:
df15.to_csv(DATA_DIR / 'model' / 'ge_2015_2017_prediction_data.csv', index=False)
df15.to_feather(DATA_DIR / 'model' / 'ge_2015_2017_prediction_data.feather')